/**
 * NamoIndia
 */
/**
 * All the app constants comes here
 */


 //*> CONFIGURATIONS
export const API_TIMEOUT = 30000;

 //*> API CALLING CONSTANTS
export const GET_API = 'GET';
export const POST_API = 'POST';
export const PUT_API = 'PUT';
export const DELETE_API = 'DELETE';
export const UPDATE_API = 'PUT';

//*> APP LOADER
export const START_SPINNER = "START_SPINNER"  
export const STOP_SPINNER = "STOP_SPINNER"

//*> ERROR MODAL
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL"  
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL"

//*> LOGIN MODAL
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL"  
export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL"
export const LOGIN_USER = "LOGIN_USER"
export const VERIFY_USER = "VERIFY_USER"
export const SAVE_LOGIN_STATUS = "SAVE_LOGIN_STATUS"
export const REMOVE_LOGIN_STATUS = "REMOVE_LOGIN_STATUS"
export const RESEND_OTP = "RESEND_OTP"
export const GET_PROFILE = "GET_PROFILE"
export const SAVE_PROFILE = "SAVE_PROFILE"
export const SAVE_USER_LOCATION = "SAVE_USER_LOCATION"
export const SAVE_USER_DEPO = "SAVE_USER_DEPO"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const GET_ADDRESS_LIST = "GET_ADDRESS_LIST"
export const ADD_ADDRESS = "ADD_ADDRESS"
export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const DELETE_ADDRESS = "DELETE_ADDRESS"
export const GET_CITY_LIST = "GET_CITY_LIST"
export const SEND_DEVICE_TOKEN = "SEND_DEVICE_TOKEN"
export const LOGOUT_USER = "LOGOUT_USER"

//*> HOME SCREEN CONSTANTS
export const GET_HOME_SCREEN_DATA = "GET_HOME_SCREEN_DATA"
export const SET_HOME_SCREEN_CATEGORIES = "SET_HOME_SCREEN_CATEGORIES"
export const SET_HOME_SCREEN_TODAY_DEAL = "SET_HOME_SCREEN_TODAY_DEAL"

//*> PRODUCT SCREEN CONSTANTS
export const GET_PRODUCT_SCREEN_LIST = "GET_PRODUCT_SCREEN_LIST"

//*> PRODUCT DETAIL SCREEN CONSTANTS
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const NOTIFY_ME_ABOUT_PRODUCT = "NOTIFY_ME_ABOUT_PRODUCT"

//*> CART SCREEN CONSTANTS
export const UPDATE_CART = "UPDATE_CART"
export const GET_CART_DETAILS = "GET_CART_DETAILS"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const VERIFY_PRODUCT_ITEMS = "VERIFY_PRODUCT_ITEMS"
export const REMOVE_PRODUCT_ITEMS = "REMOVE_PRODUCT_ITEMS"

//*> CHECKOUT SCREEN CONSTANTS
export const GET_CHECKOUT_DETAILS = "GET_CHECKOUT_DETAILS"
export const CREATE_RAZORPAY_PAYMENTS = 'CREATE_RAZORPAY_PAYMENTS';
export const VERIFY_RAZORPAY_PAYMENTS = 'VERIFY_RAZORPAY_PAYMENTS';

//*> MY ORDERS CONSTANTS
export const MY_ORDERS_LIST = "MY_ORDERS_LIST"
export const MY_ORDERS_DETAILS = "MY_ORDERS_DETAILS"

//*> COUPONS & REWARDS CONSTANTS
export const GET_REWARDS_LIST = "GET_REWARDS_LIST"

//*> NOTIFICATIONS CONSTANTS
export const GET_NOTIFICATIONS_LIST = "GET_NOTIFICATIONS_LIST"
export const SUBMIT_ORDER_FEEDBACK = "SUBMIT_ORDER_FEEDBACK"
export const CANCEL_ORDER = "CANCEL_ORDER"
export const REORDER_PRODUCT = "REORDER_PRODUCT"
export const EXCHANGE_PRODUCT = "EXCHANGE_PRODUCT"